[[plugins]]
package = "netlify-plugin-inline-source"

[build.environment]
  NETLIFY_GA_ID = "${NETLIFY_GA_ID}"

[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true

[context.production]
  environment = { NETLIFY_GA_ID = "G-XXXXXXXXXX" }
